module.exports={
    devServer:{
        host:'localhost',
        port:'8080',
        proxy:{
            '/api':{
                target:'https://wwww.imooc.com/',
                changeOrigin:true,
                pathRewrite:{
                    '/api':''
                }
            }
        }
    }
}