// module.exports={
//     devServe:{
//         host:'localhost',
//         port:'8080',
//         proxy:{
//             '/api':{
//                 target:'https://order.imooc.com/',
//                 changeOrigin:true,
//                 pathRewrite:{
//                     '/api':'/api'
//                 }
//             }
//         }
//     }
// }